config/routes.rb
ChamaProBackend::Application.routes.draw do
  resources :table_indices

  resources :clients

  resources :balances

  resources :groups

  resources :managerscashes

  resources :transactions

  resources :users
  
  root :to => "table_indices#index"

end

app/models/balance.rb
class Balance < ActiveRecord::Base
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  # GET /balances
  # GET /balances.xml
  def index
    @balances = Balance.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @balances }
      format.json  { render :json => @balances }
    end
  end

  # GET /balances/1
  # GET /balances/1.xml
  def show
    @balance = Balance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @balance }
      format.json  { render :json => @balance }
    end
  end

  # GET /balances/new
  # GET /balances/new.xml
  def new
    @balance = Balance.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @balance }
      format.json  { render :json => @balance }
    end
  end

  # GET /balances/1/edit
  def edit
    @balance = Balance.find(params[:id])
  end

  # POST /balances
  # POST /balances.xml
  def create
    @balance = Balance.new(params[:balance])

    respond_to do |format|
      if @balance.save
        format.html { redirect_to(@balance, :notice => 'Balance was successfully created.') }
        format.xml  { render :xml => @balance, :status => :created, :location => @balance }
        format.json  { render :json => @balance, :status => :created, :location => @balance }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @balance.errors, :status => :unprocessable_entity }
        format.json  { render :json => @balance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /balances/1
  # PUT /balances/1.xml
  def update
    @balance = Balance.find(params[:id])

    respond_to do |format|
      if @balance.update_attributes(params[:balance])
        format.html { redirect_to(@balance, :notice => 'Balance was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @balance.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /balances/1
  # DELETE /balances/1.xml
  def destroy
    @balance = Balance.find(params[:id])
    @balance.destroy

    respond_to do |format|
      format.html { redirect_to(balances_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/balances_helper.rb
module BalancesHelper
end

app/views/balances/_form.html.erb
<%= form_for(@balance) do |f| %>
  <% if @balance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@balance.errors.count, "error") %> prohibited this balance from being saved:</h2>

      <ul>
      <% @balance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cliend_ID %><br />
    <%= f.text_field :cliend_ID %>
  </div>
  <div class="field">
    <%= f.label :balance %><br />
    <%= f.text_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/balances/edit.html.erb
<h1>Editing balance</h1>

<%= render 'form' %>

<%= link_to 'Show', @balance %> |
<%= link_to 'Back', balances_path %>

app/views/balances/index.html.erb
<h1>Listing balances</h1>

<table>
  <tr>
    <th>Cliend id</th>
    <th>Balance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @balances.each do |balance| %>
  <tr>
    <td><%= balance.cliend_ID %></td>
    <td><%= balance.balance %></td>
    <td><%= link_to 'Show', balance %></td>
    <td><%= link_to 'Edit', edit_balance_path(balance) %></td>
    <td><%= link_to 'Destroy', balance, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Balance', new_balance_path %>

app/views/balances/new.html.erb
<h1>New balance</h1>

<%= render 'form' %>

<%= link_to 'Back', balances_path %>

app/views/balances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cliend id:</b>
  <%= @balance.cliend_ID %>
</p>

<p>
  <b>Balance:</b>
  <%= @balance.balance %>
</p>


<%= link_to 'Edit', edit_balance_path(@balance) %> |
<%= link_to 'Back', balances_path %>